name: Publish
on:
  push:
    tags: 
      - 'v*'

jobs:
    publish:
      name: publish
      environment: production
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Publish
          uses: actions/setup-go@v4
          with:
            go-version: '1.22.1'
            cache: false
          run: |
            export GOPROXY=proxy.golang.org 
            go list -m example.com/mymodule@${{ github.ref_name }}
